### ISSUE TITLE
Improve doc: how to use the Orb

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost-community/mattermost-plugin-circleci#14]
Links : 
- [nathanaelhoun/circleci-orb-mattermost-plugin-notify](https://github.com/nathanaelhoun/circleci-orb-mattermost-plugin-notify)
- [Approve a job in CircleCI](https://circleci.com/blog/manual-job-approval-and-scheduled-workflow-runs/)

**Comment by nathanaelhoun** [comment]
@pradeepmurugesan @darkLord19 Should we put this documentation in a Github Wiki or in a `HOW_TO.md` in the repo?

**Comment by darkLord19** [comment]
I prefer it to be in HOW_TO.md or README.md. Not a fan of vendor specific wikis and such!
