### ISSUE TITLE
Warn when an environment variable will be overwritten

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost-community/mattermost-plugin-circleci#39]
**Is your feature request related to a problem? Please describe.**

When setting an environnment variable that already exists, the old value is delete without warning.
![image](https://user-images.githubusercontent.com/45119518/95019964-b223fb00-0668-11eb-917b-f157b8bb8f96.png)

**Describe the solution you'd like**

The plugin should ask to validate / ask to delete the old variable before setting a new value

**Comment by nathanaelhoun** [comment]
@darkLord19 What do you think?

**Comment by darkLord19** [comment]
Great Thought! This will be a good value edition! I Will work on it.
