### ISSUE TITLE
Send "channel subscribed" and "channel unsuscribed" as real posts (not ephemeral)

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost-community/mattermost-plugin-circleci#44]
As these actions concern the whole channel, they should be logged as real posts.
The "How to finish setup" when subscribing may be kept as ephemeral, because it contains a secret and doesn't concern all the channel.

**Comment by nathanaelhoun** [comment]
@darkLord19 @pradeepmurugesan What do you think?

**Comment by darkLord19** [comment]
Yes that makes sense.
