### ISSUE TITLE
Check the generated webhook secret

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost-community/mattermost-plugin-circleci#45]
Sometimes, the webhook secret contains a `/` character. This make the router to be confused, and the webhooks never arrive.
We should check the webhook secret value before validation
![image](https://user-images.githubusercontent.com/45119518/95026986-6dfb1f80-0695-11eb-881d-910ccec84b51.png)

**Comment by darkLord19** [comment]
This is a tricky one. let's add it in documentation till we get some fix out.

**Comment by nathanaelhoun** [comment]
Discussion on [Mattermost Community](https://community-daily.mattermost.com/core/pl/nq8btghc37gzxk7tca5gjwtmoa)
